spring:
  application:
    name: video-service
  datasource:
    url: jdbc:mysql://54.153.147.252:3306/video_service?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: reelsRestDba123
    hikari:
      idle-timeout: '30000'
      minimum-idle: '5'
      maximum-pool-size: '50'
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
tiktok:
  save-path: D:\vidTiltok\
  url: https://www.tiktok.com/
  snaptik-url: https://snaptik.app/
  driver-path: C:\Users\hunte\Downloads\chromedriver_win32\chromedriver.exe
  download-rage: 10
